### ISSUE TITLE
Possible to export images in spherical format

### ISSUE THREAD

**Issue by Coppershorre** [smcameron/gaseous-giganticus#8]
Is it possible for the program to export in a spherical format rather than a cube map format?

**Comment by smcameron** [comment]
Not sure what you mean by "spherical" format, perhaps you mean an equirectangular projection.  Currently it only exports cube map images.  Some people use Hugin ( http://hugin.sourceforge.net/ ) to transform the cubemap images to equirectangular.

**Comment by smcameron** [comment]
It occurs to me that by "spherical format", perhaps you meant an image like this:

![p](https://user-images.githubusercontent.com/23912/148816230-705a08a4-6b90-4ff3-bb5f-2e284d66fc0f.jpg)

If that's what you meant, then I am afraid that is not in the cards, because that means adding a 3D renderer, and gaseous-giganticus is just meant to generate textures, not display them.

If that's not what you meant, and you really meant an equirectangular projection, that would be a reasonable feature to add.

**Comment by smcameron** [comment]
* a490739c7d54fb20dd5195f473e6f726218f456b  Allow exporting equirectangular images 

Now gaseous-giganticus can export equirectangular images if the '-E' option is specified.  You must specify the height of the image (e.g., -E 1024).  The width will be twice the height.

If you meant something else by "spherical format", feel free to re-open this issue.
